version: '3.1'
services:
  filebeat:
    image: elastic/filebeat:7.17.5
    container_name: filebeat
    hostname: filebeat
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - ./nginx:/usr/share/filebeat/nginx
      - ./conf/filebeat.yml:/usr/share/filebeat/filebeat.yml 
        #      - ./data:/usr/share/filebeat/data 
        #      - ./logs:/usr/share/filebeat/logs
    working_dir: /usr/share/filebeat
    command: filebeat -e -c /usr/share/filebeat/filebeat.yml

  nginx:
    image: nginx:1.23.3
    restart: always
    container_name: filebeat-nginx
    environment:
      TZ: Asia/Shanghai
    ports:
      - 30080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    privileged: true
